apiVersion: skaffold/v2alpha3
kind: Config
deploy: 
    kubectl:
        manifests: 
            -   ./infra/k8s/*
build:
    local:
        push:   false
    artifacts: 
        -   image: romanwhales/client
            context: client
            docker:
                dockerfile: Dockerfile
            sync:
                manual: 
                    -   src: 'src/**/*.js'
                        dest: .
        -   image: romanwhales/comments
            context: comments
            docker:
                dockerfile: Dockerfile
            sync:
                manual: 
                    -   src: '*.js'
                        dest: .
        -   image: romanwhales/event-bus
            context: event-bus
            docker:
                dockerfile: Dockerfile
            sync:
                manual: 
                    -   src: '*.js'
                        dest: .
        -   image: romanwhales/moderation
            context: moderation
            docker:
                dockerfile: Dockerfile
            sync:
                manual: 
                    -   src: '*.js'
                        dest: .
        -   image: romanwhales/posts
            context: posts
            docker:
                dockerfile: Dockerfile
            sync:
                manual: 
                    -   src: '*.js'
                        dest: .
        -   image: romanwhales/query
            context: query
            docker:
                dockerfile: Dockerfile
            sync:
                manual: 
                    -   src: '*.js'
                        dest: .
